name: Release Chrome Extension

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # or "latest", "canary", <sha>

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: bun install

      - name: Build with Chrome Extension
        run: bun run build

      - name: Find build artifact
        id: find_zip
        run: |
          FILE=$(ls release/crx-*.zip | head -n 1)
          echo "zip_file=$FILE" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: ${{ steps.find_zip.outputs.zip_file }}

  # Release job
  release:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: crx-*.zip
